import type { SkillSequence } from './sequence-types'

export interface CodegenOptions {
  presetImportPath: string
  /** Optional path that exports `AllPresetParticles` for the host project. */
  allParticlesImportPath?: string
  componentName?: string
}

export interface GeneratedSkill {
  filename: string
  code: string
}

function toPascalCase(name: string): string {
  return name
    .replace(/[^a-zA-Z0-9 ]/g, ' ')
    .split(/\s+/)
    .filter(Boolean)
    .map(w => w.charAt(0).toUpperCase() + w.slice(1).toLowerCase())
    .join('')
}

export function generateSkillComponent(seq: SkillSequence, opts: CodegenOptions): GeneratedSkill {
  const name = opts.componentName || toPascalCase(seq.name) || 'MySkill'
  const filename = `${name}.tsx`
  const seqJson = JSON.stringify(seq, null, 2)
  const allParticlesPath = opts.allParticlesImportPath ?? './all-preset-particles'

  const code = `\
import { useRef, useState, useContext } from 'react'
import { useFrame } from '@react-three/fiber'
import { useVFXStore } from 'r3f-vfx'
import { presetById } from '${opts.presetImportPath}'
import { AllPresetParticles } from '${allParticlesPath}'
import { MeshlineEffect } from './meshline-effect'
import { SkillEngineCtx } from './engine-adapters'

// Auto-generated by VFX Playground — Skill Sequencer
// Skill: ${seq.name}${seq.description ? `\n// ${seq.description}` : ''}
//
// Persistent pattern: <AllPresetParticles> mounts every preset once with
// autoStart=false. Particle clips fire via useVFXStore.emit() (edge-trigger).
// Meshline clips still mount on demand (no compute pipeline → mount-safe).
//
// Integration:
//   1. Render <AllPresetParticles> inside your Canvas (or import the playground's).
//   2. Mount this <${name}> component to play the skill.
//   3. Provide SkillEngineCtx with onHit / camera / sfx adapters.

const SEQUENCE = ${seqJson} as const

type Clip = (typeof SEQUENCE.clips)[number]

function computeEmitCount(props: Record<string, unknown>): number {
  const lt = props.lifetime as [number, number] | number | undefined
  const avg = Array.isArray(lt) ? (lt[0] + lt[1]) / 2 : typeof lt === 'number' ? lt : 1
  const max = (props.maxParticles as number | undefined) ?? 100
  return Math.min(8, Math.max(1, Math.ceil(max / (Math.max(0.01, avg) * 60))))
}

const STRUCTURAL_KEYS = new Set([
  'maxParticles', 'lighting', 'appearance', 'shadow', 'orientToDirection',
  'lightingParams', 'geometryNode', 'geometry', 'curveTexturePath',
  'depthTest', 'renderOrder', 'name', 'debug',
])

function pickOverrides(props: Record<string, unknown>): Record<string, unknown> {
  const out: Record<string, unknown> = {}
  for (const k of Object.keys(props)) {
    if (!STRUCTURAL_KEYS.has(k)) out[k] = props[k]
  }
  return out
}

export interface ${name}Props {
  onHit?: (clipKind: string) => void
  onComplete?: () => void
  autoPlay?: boolean
}

export function ${name}({ onHit, onComplete, autoPlay = true }: ${name}Props) {
  const engine = useContext(SkillEngineCtx)
  const [liveClips, setLiveClips] = useState<Clip[]>([])
  const timeRef = useRef(0)
  const playingRef = useRef(autoPlay)
  const firedRef = useRef<Set<string>>(new Set())

  useFrame((_, delta) => {
    if (!playingRef.current) return
    timeRef.current += delta * 1000
    const t = timeRef.current

    setLiveClips(SEQUENCE.clips.filter(c => t >= c.start && t < c.start + c.duration) as Clip[])

    for (const c of SEQUENCE.clips) {
      if (t >= c.start && !firedRef.current.has(c.id)) {
        firedRef.current.add(c.id)

        if (c.track === 'vfx') {
          const preset = (presetById as Record<string, any>)[c.kind]
          if (preset && preset.kind !== 'meshline') {
            const props = preset.props as Record<string, unknown>
            const pos = ((c.payload as any)?.position as [number, number, number] | undefined) ?? [0, 0, 0]
            useVFXStore.getState().emit(c.kind, {
              x: pos[0], y: pos[1], z: pos[2],
              count: computeEmitCount(props),
              overrides: pickOverrides(props),
            })
          }
        }

        if (c.track === 'event' && c.kind === 'onHit') onHit?.(c.kind)
        if (c.track === 'camera' && c.kind === 'shake')
          engine?.triggerCameraShake({ intensity: ((c.payload as any)?.intensity as number) ?? 0.3, freq: ((c.payload as any)?.freq as number) ?? 30, duration: c.duration })
        if (c.track === 'time' && c.kind === 'hitstop')
          engine?.triggerHitStop(c.duration)
        if (c.track === 'flash')
          engine?.flashScreen(((c.payload as any)?.color as string) ?? '#ffffff', ((c.payload as any)?.alpha as number) ?? 0.5, c.duration)
        if (c.track === 'sfx')
          engine?.playSfx(c.kind, c.payload as Record<string, unknown>)
      }
    }

    if (t >= SEQUENCE.duration) {
      playingRef.current = false
      onComplete?.()
    }
  })

  // Meshline clips still mount on demand (no compute pipeline).
  const meshlineClips = liveClips.filter(c => {
    if (c.track !== 'vfx') return false
    const p = (presetById as Record<string, any>)[c.kind]
    return p?.kind === 'meshline'
  })
  const uniqueMeshlines = Array.from(new Map(meshlineClips.map(c => [c.kind, c])).values())

  return (
    <>
      <AllPresetParticles />
      {uniqueMeshlines.map(clip => {
        const preset = (presetById as Record<string, any>)[clip.kind]
        return <MeshlineEffect key={clip.kind} preset={preset} />
      })}
    </>
  )
}
`
  return { filename, code }
}
