/**
 * Pure function: serializes Zustand scene state → BiomeConfig TypeScript string.
 * Output can be pasted directly into src/scene/arena-biome-config.ts.
 */
import type { PlacedProp, BgLayerConfig, LightingConfig, VFXPlacement, DioramaConfig } from '../store/scene-types'

export interface GenerateOptions {
  biome: 'cave' | 'forest'
  configName: string
  diorama?: DioramaConfig | null
  placedProps: PlacedProp[]
  bgLayers: BgLayerConfig[]
  lighting: LightingConfig
  vfxPlacements: VFXPlacement[]
}

/** Strip game-assets prefix — main game uses bare paths */
function stripPrefix(src: string): string {
  return src.startsWith('/game-assets') ? src.slice('/game-assets'.length) : src
}

/** Format number: strip trailing zeros, max 4 decimal places */
function n(v: number): string {
  return parseFloat(v.toFixed(4)).toString()
}

/** Format [x, y, z] tuple */
function vec3(v: [number, number, number]): string {
  return `[${n(v[0])}, ${n(v[1])}, ${n(v[2])}]`
}

function generateProp3D(prop: PlacedProp): string {
  const src = stripPrefix(prop.src)
  const hasRotation = prop.rotation.some((v) => v !== 0)
  const rotation = hasRotation ? `\n      rotation: ${vec3(prop.rotation)},` : ''
  const light = prop.light
    ? `\n      light: { offsetY: ${n(prop.light.offsetY)}, color: '${prop.light.color}', intensity: ${n(prop.light.intensity)}, distance: ${n(prop.light.distance)} },`
    : ''
  return `    { src: '${src}', position: ${vec3(prop.position)},${rotation} scale: ${n(prop.scale as number)},${light} },`
}

function generateBgLayer(layer: BgLayerConfig): string {
  const src = stripPrefix(layer.src)
  return `    { src: '${src}', z: ${n(layer.z)}, y: ${n(layer.y)}, scale: ${n(layer.scale)}, opacity: ${n(layer.opacity)} },`
}

function generateVFXPlacement(vfx: VFXPlacement): string {
  return `    { effectId: '${vfx.effectId}', position: ${vec3(vfx.position)}, scale: ${n(vfx.scale)} },`
}

export function generateBiomeConfig(opts: GenerateOptions): string {
  const { biome, configName, diorama, placedProps, bgLayers, lighting, vfxPlacements } = opts
  const groundColor = biome === 'cave' ? '#2a2a30' : '#3a5a2a'

  const lines: string[] = [
    `// ✅ Generated by Map Playground — paste into arena-biome-config.ts`,
    `const ${configName}: BiomeConfig = {`,
    `  biome: '${biome}',`,
    `  groundColor: '${groundColor}',`,
    `  ambient: { intensity: ${n(lighting.ambient.intensity)}, color: '${lighting.ambient.color}' },`,
    `  directional: { intensity: ${n(lighting.directional.intensity)}, color: '${lighting.directional.color}', position: ${vec3(lighting.directional.position)} },`,
    `  fogColor: '${lighting.fogColor}',`,
    `  vignette: { strength: ${n(lighting.vignette.strength)} },`,
  ]

  // bgLayers
  if (bgLayers.length > 0) {
    lines.push(`  bgLayers: [`)
    bgLayers.forEach((l) => lines.push(generateBgLayer(l)))
    lines.push(`  ],`)
  } else {
    lines.push(`  bgLayers: [],`)
  }

  lines.push(`  props: [],`)

  // diorama
  if (diorama) {
    const src = stripPrefix(diorama.src)
    lines.push(`  diorama: '${src}',`)
    lines.push(`  dioramaScale: ${n(diorama.scale)},`)
    lines.push(`  dioramaY: ${n(diorama.y)},`)
  }

  // props3D
  if (placedProps.length > 0) {
    lines.push(`  props3D: [`)
    placedProps.forEach((p) => lines.push(generateProp3D(p)))
    lines.push(`  ],`)
  } else {
    lines.push(`  props3D: [],`)
  }

  // atmosphericVFX — only emit when present
  if (vfxPlacements.length > 0) {
    lines.push(`  atmosphericVFX: [`)
    vfxPlacements.forEach((v) => lines.push(generateVFXPlacement(v)))
    lines.push(`  ],`)
  }

  lines.push(`};`)
  return lines.join('\n')
}
