import { EmitterShape, Blending } from 'r3f-vfx'
import type { VfxPreset } from '../preset-types'

// Đế Quốc — Electric/Steam/Tech empire
// Colors: primary=#1a1a2e, accent=#00d4ff
export const deQuocPresets: VfxPreset[] = [
  {
    id: 'dq-spark',
    name: 'Điện Hoa (Electric Spark)',
    category: 'de-quoc',
    categoryLabel: 'Đế Quốc',
    emoji: '⚡',
    description: 'Sharp electric sparks, cyan additive',
    props: {
      maxParticles: 1500,
      size: [0.02, 0.06],
      colorStart: ['#00d4ff', '#ffffff'],
      colorEnd: ['#0088ff'],
      fadeOpacity: [1, 0],
      lifetime: [0.1, 0.4],
      speed: [0.5, 1.5],
      gravity: [0, -1, 0],
      emitterShape: EmitterShape.SPHERE,
      emitterRadius: [0, 0.3],
      startPositionAsDirection: true,
      blending: Blending.ADDITIVE,
      intensity: 8,
    },
  },
  {
    id: 'dq-lightning-trail',
    name: 'Lôi Tích (Lightning Trail)',
    category: 'de-quoc',
    categoryLabel: 'Đế Quốc',
    emoji: '🌩️',
    description: 'Sustained plasma trail with bright cyan core',
    props: {
      maxParticles: 800,
      size: [0.08, 0.15],
      colorStart: ['#00d4ff', '#66eeff'],
      colorEnd: ['#4400ff'],
      fadeOpacity: [1, 0],
      lifetime: [0.3, 0.8],
      speed: [0.2, 0.6],
      turbulence: { intensity: 2.0, frequency: 1.5, speed: 1.0 },
      blending: Blending.ADDITIVE,
      intensity: 6,
    },
  },
  {
    id: 'dq-steam',
    name: 'Hơi Thép (Steam Vent)',
    category: 'de-quoc',
    categoryLabel: 'Đế Quốc',
    emoji: '♨️',
    description: 'Industrial steam venting upward',
    props: {
      maxParticles: 300,
      size: [0.3, 0.6],
      colorStart: ['#ccccdd', '#aaaacc'],
      colorEnd: ['#666688'],
      fadeSize: [0.5, 1.5],
      fadeOpacity: [0.6, 0],
      gravity: [0, 0.8, 0],
      lifetime: [2, 4],
      direction: [[-0.1, 0.1], [0.8, 1], [-0.1, 0.1]],
      speed: [0.03, 0.08],
      emitterShape: EmitterShape.DISK,
      emitterRadius: [0, 0.3],
      turbulence: { intensity: 0.8, frequency: 0.5, speed: 0.2 },
    },
  },
  {
    id: 'dq-overcharge',
    name: 'Quá Tải (Overcharge)',
    category: 'de-quoc',
    categoryLabel: 'Đế Quốc',
    emoji: '💥',
    description: '"Điện Thế Chỉ Huy" passive — massive electric discharge',
    props: {
      maxParticles: 2000,
      size: [0.05, 0.2],
      colorStart: ['#00d4ff', '#ffffff'],
      colorEnd: ['#8800ff', '#000033'],
      fadeOpacity: [1, 0],
      lifetime: [0.3, 1.0],
      speed: [0.5, 2.0],
      gravity: [0, -0.5, 0],
      emitterShape: EmitterShape.SPHERE,
      emitterRadius: [0.5, 1.5],
      startPositionAsDirection: true,
      blending: Blending.ADDITIVE,
      intensity: 12,
      turbulence: { intensity: 3.0, frequency: 2.0, speed: 1.5 },
    },
  },
]
