import { EmitterShape, Blending } from 'r3f-vfx'
import type { VfxPreset } from '../preset-types'

// Generic combat/utility effects for all civilizations
export const genericPresets: VfxPreset[] = [
  {
    id: 'gen-hit',
    name: 'Hit Impact',
    category: 'generic',
    categoryLabel: 'Generic',
    emoji: '💢',
    description: 'Universal hit flash with debris',
    props: {
      maxParticles: 500,
      size: [0.05, 0.1],
      colorStart: ['#fb1818', '#ffee88'],
      colorEnd: ['#ff8800'],
      fadeOpacity: [0.8, 0],
      lifetime: [2.5, 0.2],
      speed: [0.885, 1.0],
      gravity: [0, -2, 0],
      emitterShape: EmitterShape.SPHERE,
      emitterRadius: [1.75, 0.5],
      startPositionAsDirection: true,
      blending: Blending.MULTIPLY,
      appearance: "circular",
      intensity: 4,
      collision: { plane: { y: 0 }, bounce: 0.3, friction: 0.4 },
    },
  },
  {
    id: 'gen-burst',
    name: 'Explosion Burst',
    category: 'generic',
    categoryLabel: 'Generic',
    emoji: '💥',
    description: 'Radial explosion with ground bounce',
    props: {
      maxParticles: 1000,
      size: [0.08, 0.2],
      colorStart: ['#ff8800', '#ffcc00'],
      colorEnd: ['#cc2200', '#330000'],
      fadeOpacity: [1, 0],
      lifetime: [0.3, 1.0],
      speed: [0.5, 1.5],
      gravity: [0, -3, 0],
      emitterShape: EmitterShape.SPHERE,
      emitterRadius: [0, 0.5],
      startPositionAsDirection: true,
      blending: Blending.ADDITIVE,
      intensity: 6,
      collision: { plane: { y: 0 }, bounce: 0.4, friction: 0.3 },
    },
  },
  {
    id: 'gen-trail',
    name: 'Movement Trail',
    category: 'generic',
    categoryLabel: 'Generic',
    emoji: '🌀',
    description: 'Persistent movement trail with fade',
    props: {
      maxParticles: 400,
      size: [0.04, 0.1],
      colorStart: ['#66bbff', '#aaddff'],
      colorEnd: ['#2244aa'],
      fadeOpacity: [0.7, 0],
      lifetime: [0.5, 1.5],
      speed: [0.05, 0.08],
      turbulence: { intensity: 0.5, frequency: 1, speed: 0.5 },
    },
  },
  {
    id: 'gen-trail-fire',
    name: 'Weapon Trail Fire',
    category: 'generic',
    categoryLabel: 'Generic',
    emoji: '🔥',
    description: 'Tiny fire particles trailing a moving weapon tip',
    props: {
      maxParticles: 200,
      size: [0.08, 0.2],
      colorStart: ['#ff6600', '#ffaa00', '#ff2200'],
      colorEnd: ['#cc2200', '#330000'],
      fadeOpacity: [1, 0],
      gravity: [0, 0.4, 0],
      lifetime: [0.2, 0.4],
      direction: [[-0.1, 0.1], [0.5, 1.0], [-0.1, 0.1]],
      speed: [0.01, 0.06],
      friction: { intensity: 0.05, easing: 'easeOut' },
      blending: Blending.ADDITIVE,
      intensity: 3,
    },
  },
  {
    id: 'gen-trail-lance',
    name: 'Lance Air Wake',
    category: 'generic',
    categoryLabel: 'Generic',
    emoji: '💨',
    description: 'Perpendicular air-disturbance wake behind a horizontal lance thrust',
    props: {
      maxParticles: 400,
      size: [0.08, 0.22],
      colorStart: ['#aaddff', '#ffffff', '#66bbff'],
      colorEnd: ['#002266'],
      fadeOpacity: [0.9, 0],
      gravity: [0, -0.3, 0],
      lifetime: [0.20, 0.50],
      // Dominant ±Y (up+down equally) perpendicular to horizontal lance;
      // small X/Z for organic feel. Speed calibrated to ls-fire range for visible movement.
      direction: [[-0.15, 0.15], [-1.2, 1.2], [-0.3, 0.3]],
      speed: [0.01, 0.06],
      blending: Blending.ADDITIVE,
      intensity: 5,
    },
  },
  {
    id: 'gen-levelup',
    name: 'Level Up',
    category: 'generic',
    categoryLabel: 'Generic',
    emoji: '⭐',
    description: 'Celebratory rising golden stars',
    props: {
      maxParticles: 600,
      size: [0.08, 0.2],
      colorStart: ['#ffdd00', '#ffffff'],
      colorEnd: ['#ff8800'],
      fadeSize: [0.5, 1.5],
      fadeOpacity: [1, 0],
      gravity: [0, 1.5, 0],
      lifetime: [1, 3],
      speed: [0.05, 0.15],
      emitterShape: EmitterShape.DISK,
      emitterRadius: [0.3, 1.0],
      startPositionAsDirection: true,
      blending: Blending.ADDITIVE,
      intensity: 5,
    },
  },
]
