import type { MeshlinePreset } from '../preset-types'

/**
 * Meshline-based weapon FX presets — slash arcs, beams, projectile trails.
 * Built on `makio-meshline`. Use additive + bloom for the best look.
 */
export const meshlinePresets: MeshlinePreset[] = [
  {
    id: 'ml-slash-horizontal',
    kind: 'meshline',
    name: 'Horizontal Slash',
    category: 'weapon-fx',
    categoryLabel: 'Weapon FX',
    emoji: '⚔️',
    description: 'Wide horizontal sword slash arc',
    shape: 'arc',
    shapeParams: { segments: 48, radius: 1.4, arcAngle: Math.PI * 0.85 },
    color: '#ffffff',
    gradientColor: '#88ccff',
    lineWidth: 18,
    opacity: 0.95,
    additive: true,
    rotation: [0, 0, 0],
  },
  {
    id: 'ml-slash-diagonal',
    kind: 'meshline',
    name: 'Diagonal Slash',
    category: 'weapon-fx',
    categoryLabel: 'Weapon FX',
    emoji: '🗡️',
    description: 'Top-down katana slash',
    shape: 'arc',
    shapeParams: { segments: 48, radius: 1.6, arcAngle: Math.PI * 0.75 },
    color: '#ffeecc',
    gradientColor: '#ff6644',
    lineWidth: 14,
    opacity: 1,
    additive: true,
    rotation: [0, 0, Math.PI * 0.35],
  },
  {
    id: 'ml-slash-spin',
    kind: 'meshline',
    name: 'Spin Slash (full circle)',
    category: 'weapon-fx',
    categoryLabel: 'Weapon FX',
    emoji: '🌀',
    description: 'Full 360° whirlwind slash',
    shape: 'circle',
    shapeParams: { segments: 64, radius: 1.5 },
    color: '#aaffee',
    gradientColor: '#3388ff',
    lineWidth: 12,
    opacity: 0.85,
    additive: true,
    rotation: [Math.PI / 2, 0, 0],
  },
  {
    id: 'ml-beam-laser',
    kind: 'meshline',
    name: 'Laser Beam',
    category: 'weapon-fx',
    categoryLabel: 'Weapon FX',
    emoji: '⚡',
    description: 'Straight high-energy beam',
    shape: 'line',
    shapeParams: {
      segments: 32,
      start: [0, 0, 0],
      end: [4, 0, 0],
    },
    color: '#ffffff',
    gradientColor: '#00ffcc',
    lineWidth: 22,
    opacity: 1,
    additive: true,
  },
  {
    id: 'ml-beam-lightning',
    kind: 'meshline',
    name: 'Lightning Bolt',
    category: 'weapon-fx',
    categoryLabel: 'Weapon FX',
    emoji: '⚡',
    description: 'Jagged sine-wave lightning',
    shape: 'sine',
    shapeParams: { wavelengths: 6, segments: 96, amplitude: 0.25, length: 4 },
    color: '#ffffff',
    gradientColor: '#88ddff',
    lineWidth: 10,
    opacity: 0.95,
    additive: true,
  },
  {
    id: 'ml-projectile-trail',
    kind: 'meshline',
    name: 'Projectile Trail',
    category: 'weapon-fx',
    categoryLabel: 'Weapon FX',
    emoji: '💫',
    description: 'Tapered trail for fast projectile',
    shape: 'line',
    shapeParams: {
      segments: 32,
      start: [-2, 0, 0],
      end: [0, 0, 0],
    },
    color: '#ffaa44',
    gradientColor: '#ff2200',
    lineWidth: 14,
    opacity: 0.9,
    additive: true,
  },
  {
    id: 'ml-spiral-charge',
    kind: 'meshline',
    name: 'Spiral Charge-up',
    category: 'weapon-fx',
    categoryLabel: 'Weapon FX',
    emoji: '🌪️',
    description: 'Helix spiral wrapping a target',
    shape: 'spiral',
    shapeParams: { segments: 128, radius: 1.0, spiralTurns: 4, spiralHeight: 2 },
    color: '#ffffff',
    gradientColor: '#cc44ff',
    lineWidth: 8,
    opacity: 0.85,
    additive: true,
  },

  // ─── Linh Sơn ult meshline kit (Đồng Cổ Thất Trảm) ─────────────────
  {
    id: 'ls-bronze-drum-mark',
    kind: 'meshline',
    name: 'Trống Đồng (Bronze Drum Sigil)',
    category: 'weapon-fx',
    categoryLabel: 'Weapon FX',
    emoji: '🥁',
    description: 'Flat ground sigil — bronze drum ring (Linh Sơn ult)',
    shape: 'circle',
    shapeParams: { segments: 96, radius: 2.4 },
    color: '#fff1c0',
    gradientColor: '#D4A017',
    lineWidth: 26,
    opacity: 0.9,
    additive: true,
    rotation: [Math.PI / 2, 0, 0],
  },
  {
    id: 'ls-bronze-drum-inner',
    kind: 'meshline',
    name: 'Trống Đồng — Vòng Trong (Inner Ring)',
    category: 'weapon-fx',
    categoryLabel: 'Weapon FX',
    emoji: '🥁',
    description: 'Inner concentric ring of bronze drum sigil',
    shape: 'circle',
    shapeParams: { segments: 64, radius: 1.4 },
    color: '#ffe080',
    gradientColor: '#aa7000',
    lineWidth: 14,
    opacity: 0.85,
    additive: true,
    rotation: [Math.PI / 2, 0, 0],
  },
  {
    id: 'ls-flame-wave',
    kind: 'meshline',
    name: 'Hỏa Triều Tuyến (Flame Wave Front)',
    category: 'weapon-fx',
    categoryLabel: 'Weapon FX',
    emoji: '🔥',
    description: 'Linear flame-wave front for Linh Sơn ult finisher',
    shape: 'line',
    shapeParams: {
      segments: 64,
      start: [0, 0.2, -2.4],
      end: [0, 0.2, 2.4],
    },
    color: '#ffffff',
    gradientColor: '#ff3300',
    lineWidth: 36,
    opacity: 1,
    additive: true,
    rotation: [0, Math.PI / 2, 0],
  },
]
