// AUTO-GENERATED by scripts/pack-sprite-sheets.py — DO NOT EDIT.
// Regenerate from the per-frame source tree (before pruning) via that script.
//
// Geometry only: which grid each sprite sheet uses. The combat manifest
// (combat-sprite-resolver.ts) remains the source of anim AVAILABILITY.

export interface SheetEntry {
  /** sheet path relative to public root, leading slash (feed to assetUrl) */
  path: string;
  cols: number;
  rows: number;
  /** row index per direction; row r holds that dir's frames left-to-right */
  dirRows: string[];
  /** true loop length per direction (<= cols); loader uses this, not cols */
  frameCounts: Record<string, number>;
}

export const SPRITE_SHEET_MANIFEST: Record<string, SheetEntry> = {
  'characters/LS-SCOUT-F/attack': {
    path: '/sprites/characters/LS-SCOUT-F/animations/attack.png',
    cols: 8, rows: 1,
    dirRows: ['east'],
    frameCounts: { 'east': 8 },
  },
  'characters/LS-SCOUT-F/battle-idle': {
    path: '/sprites/characters/LS-SCOUT-F/animations/battle-idle.png',
    cols: 8, rows: 1,
    dirRows: ['east'],
    frameCounts: { 'east': 8 },
  },
  'characters/LS-SCOUT-F/blacksmith': {
    path: '/sprites/characters/LS-SCOUT-F/animations/blacksmith.png',
    cols: 8, rows: 1,
    dirRows: ['flat'],
    frameCounts: { 'flat': 8 },
  },
  'characters/LS-SCOUT-F/blocking': {
    path: '/sprites/characters/LS-SCOUT-F/animations/blocking.png',
    cols: 4, rows: 1,
    dirRows: ['east'],
    frameCounts: { 'east': 4 },
  },
  'characters/LS-SCOUT-F/death': {
    path: '/sprites/characters/LS-SCOUT-F/animations/death.png',
    cols: 9, rows: 3,
    dirRows: ['south', 'east', 'west'],
    frameCounts: { 'south': 9, 'east': 8, 'west': 7 },
  },
  'characters/LS-SCOUT-F/walking-8-frames': {
    path: '/sprites/characters/LS-SCOUT-F/animations/walking-8-frames.png',
    cols: 8, rows: 4,
    dirRows: ['north', 'south', 'east', 'west'],
    frameCounts: { 'north': 8, 'south': 8, 'east': 8, 'west': 8 },
  },
  'characters/LS-SCOUT-F/woodcutting-8-frames': {
    path: '/sprites/characters/LS-SCOUT-F/animations/woodcutting-8-frames.png',
    cols: 8, rows: 1,
    dirRows: ['east'],
    frameCounts: { 'east': 8 },
  },
  'characters/LS-SCOUT-F/working': {
    path: '/sprites/characters/LS-SCOUT-F/animations/working.png',
    cols: 8, rows: 1,
    dirRows: ['flat'],
    frameCounts: { 'flat': 8 },
  },
  'characters/LS-SWORD-M/attack': {
    path: '/sprites/characters/LS-SWORD-M/animations/attack.png',
    cols: 8, rows: 1,
    dirRows: ['east'],
    frameCounts: { 'east': 8 },
  },
  'characters/LS-SWORD-M/battle-idle': {
    path: '/sprites/characters/LS-SWORD-M/animations/battle-idle.png',
    cols: 8, rows: 1,
    dirRows: ['east'],
    frameCounts: { 'east': 8 },
  },
  'characters/LS-SWORD-M/blacksmith': {
    path: '/sprites/characters/LS-SWORD-M/animations/blacksmith.png',
    cols: 8, rows: 1,
    dirRows: ['flat'],
    frameCounts: { 'flat': 8 },
  },
  'characters/LS-SWORD-M/blocking': {
    path: '/sprites/characters/LS-SWORD-M/animations/blocking.png',
    cols: 4, rows: 1,
    dirRows: ['east'],
    frameCounts: { 'east': 4 },
  },
  'characters/LS-SWORD-M/death': {
    path: '/sprites/characters/LS-SWORD-M/animations/death.png',
    cols: 8, rows: 1,
    dirRows: ['east'],
    frameCounts: { 'east': 8 },
  },
  'characters/LS-SWORD-M/walking-8-frames': {
    path: '/sprites/characters/LS-SWORD-M/animations/walking-8-frames.png',
    cols: 8, rows: 4,
    dirRows: ['north', 'south', 'east', 'west'],
    frameCounts: { 'north': 8, 'south': 8, 'east': 8, 'west': 8 },
  },
  'characters/LS-SWORD-M/woodcutting-8-frames': {
    path: '/sprites/characters/LS-SWORD-M/animations/woodcutting-8-frames.png',
    cols: 8, rows: 1,
    dirRows: ['east'],
    frameCounts: { 'east': 8 },
  },
  'characters/LS-SWORD-M/working': {
    path: '/sprites/characters/LS-SWORD-M/animations/working.png',
    cols: 8, rows: 1,
    dirRows: ['flat'],
    frameCounts: { 'flat': 8 },
  },
  // HAND-ADDED (not produced by pack-sprite-sheets.py): the Ancestral Blessings
  // casting sheet is a custom-named single file, not a per-anim folder, so the
  // packer can't discover it. Re-add this entry if the manifest is ever regenerated.
  'characters/LS-SWORD-M/casting': {
    path: '/sprites/characters/LS-SWORD-M/animations/ancestral-casting.png',
    cols: 8, rows: 1,
    dirRows: ['east'],
    frameCounts: { 'east': 8 },
  },
  'characters/LS-SCOUT-F/casting': {
    path: '/sprites/characters/LS-SCOUT-F/animations/ancestral-casting.png',
    cols: 8, rows: 1,
    dirRows: ['east'],
    frameCounts: { 'east': 8 },
  },
  'characters/LS-WARRIOR-M/casting': {
    path: '/sprites/characters/LS-WARRIOR-M/animations/ancestral-casting.png',
    cols: 8, rows: 1,
    dirRows: ['east'],
    frameCounts: { 'east': 8 },
  },
  'characters/LS-WARRIOR-M/attack': {
    path: '/sprites/characters/LS-WARRIOR-M/animations/attack.png',
    cols: 8, rows: 1,
    dirRows: ['east'],
    frameCounts: { 'east': 8 },
  },
  'characters/LS-WARRIOR-M/battle-idle': {
    path: '/sprites/characters/LS-WARRIOR-M/animations/battle-idle.png',
    cols: 8, rows: 1,
    dirRows: ['east'],
    frameCounts: { 'east': 8 },
  },
  'characters/LS-WARRIOR-M/blacksmith': {
    path: '/sprites/characters/LS-WARRIOR-M/animations/blacksmith.png',
    cols: 8, rows: 1,
    dirRows: ['flat'],
    frameCounts: { 'flat': 8 },
  },
  'characters/LS-WARRIOR-M/blocking': {
    path: '/sprites/characters/LS-WARRIOR-M/animations/blocking.png',
    cols: 4, rows: 1,
    dirRows: ['east'],
    frameCounts: { 'east': 4 },
  },
  'characters/LS-WARRIOR-M/death': {
    path: '/sprites/characters/LS-WARRIOR-M/animations/death.png',
    cols: 8, rows: 1,
    dirRows: ['east'],
    frameCounts: { 'east': 8 },
  },
  'characters/LS-WARRIOR-M/walking-8-frames': {
    path: '/sprites/characters/LS-WARRIOR-M/animations/walking-8-frames.png',
    cols: 8, rows: 4,
    dirRows: ['north', 'south', 'east', 'west'],
    frameCounts: { 'north': 8, 'south': 8, 'east': 8, 'west': 8 },
  },
  'characters/LS-WARRIOR-M/woodcutting-8-frames': {
    path: '/sprites/characters/LS-WARRIOR-M/animations/woodcutting-8-frames.png',
    cols: 8, rows: 1,
    dirRows: ['east'],
    frameCounts: { 'east': 8 },
  },
  'characters/LS-WARRIOR-M/working': {
    path: '/sprites/characters/LS-WARRIOR-M/animations/working.png',
    cols: 8, rows: 1,
    dirRows: ['flat'],
    frameCounts: { 'flat': 8 },
  },
  'enemies/bandit/attack': {
    path: '/sprites/enemies/bandit/animations/attack.png',
    cols: 9, rows: 1,
    dirRows: ['west'],
    frameCounts: { 'west': 9 },
  },
  'enemies/bandit/block': {
    path: '/sprites/enemies/bandit/animations/block.png',
    cols: 9, rows: 1,
    dirRows: ['west'],
    frameCounts: { 'west': 9 },
  },
  'enemies/bandit/death': {
    path: '/sprites/enemies/bandit/animations/death.png',
    cols: 9, rows: 2,
    dirRows: ['east', 'west'],
    frameCounts: { 'east': 9, 'west': 9 },
  },
  'enemies/bandit/idle': {
    path: '/sprites/enemies/bandit/animations/idle.png',
    cols: 8, rows: 1,
    dirRows: ['west'],
    frameCounts: { 'west': 8 },
  },
  'enemies/bandit/running': {
    path: '/sprites/enemies/bandit/animations/running.png',
    cols: 8, rows: 2,
    dirRows: ['east', 'west'],
    frameCounts: { 'east': 8, 'west': 8 },
  },
  'enemies/bandit/skill': {
    path: '/sprites/enemies/bandit/animations/skill.png',
    cols: 9, rows: 1,
    dirRows: ['west'],
    frameCounts: { 'west': 9 },
  },
  'enemies/cave-bat/attack': {
    path: '/sprites/enemies/cave-bat/animations/attack.png',
    cols: 8, rows: 1,
    dirRows: ['west'],
    frameCounts: { 'west': 8 },
  },
  'enemies/cave-bat/death': {
    path: '/sprites/enemies/cave-bat/animations/death.png',
    cols: 8, rows: 1,
    dirRows: ['west'],
    frameCounts: { 'west': 8 },
  },
  'enemies/cave-bat/idle': {
    path: '/sprites/enemies/cave-bat/animations/idle.png',
    cols: 8, rows: 1,
    dirRows: ['west'],
    frameCounts: { 'west': 8 },
  },
  'enemies/cave-bat/walk': {
    path: '/sprites/enemies/cave-bat/animations/walk.png',
    cols: 8, rows: 1,
    dirRows: ['west'],
    frameCounts: { 'west': 8 },
  },
  'enemies/dog-robot/attack': {
    path: '/sprites/enemies/dog-robot/animations/attack.png',
    cols: 4, rows: 1,
    dirRows: ['west'],
    frameCounts: { 'west': 4 },
  },
  'enemies/dog-robot/death': {
    path: '/sprites/enemies/dog-robot/animations/death.png',
    cols: 9, rows: 1,
    dirRows: ['west'],
    frameCounts: { 'west': 9 },
  },
  'enemies/dog-robot/walk': {
    path: '/sprites/enemies/dog-robot/animations/walk.png',
    cols: 9, rows: 1,
    dirRows: ['west'],
    frameCounts: { 'west': 9 },
  },
  'enemies/drone/attack': {
    path: '/sprites/enemies/drone/animations/attack.png',
    cols: 4, rows: 1,
    dirRows: ['west'],
    frameCounts: { 'west': 4 },
  },
  'enemies/drone/death': {
    path: '/sprites/enemies/drone/animations/death.png',
    cols: 8, rows: 1,
    dirRows: ['west'],
    frameCounts: { 'west': 8 },
  },
  'enemies/drone/walk': {
    path: '/sprites/enemies/drone/animations/walk.png',
    cols: 8, rows: 1,
    dirRows: ['west'],
    frameCounts: { 'west': 8 },
  },
  'enemies/forest-spider/attack': {
    path: '/sprites/enemies/forest-spider/animations/attack.png',
    cols: 8, rows: 1,
    dirRows: ['west'],
    frameCounts: { 'west': 8 },
  },
  'enemies/forest-spider/death': {
    path: '/sprites/enemies/forest-spider/animations/death.png',
    cols: 4, rows: 1,
    dirRows: ['west'],
    frameCounts: { 'west': 4 },
  },
  'enemies/forest-spider/walk': {
    path: '/sprites/enemies/forest-spider/animations/walk.png',
    cols: 8, rows: 1,
    dirRows: ['west'],
    frameCounts: { 'west': 8 },
  },
  'enemies/moonbear/attack': {
    path: '/sprites/enemies/moonbear/animations/attack.png',
    cols: 8, rows: 1,
    dirRows: ['west'],
    frameCounts: { 'west': 8 },
  },
  'enemies/moonbear/block': {
    path: '/sprites/enemies/moonbear/animations/block.png',
    cols: 8, rows: 1,
    dirRows: ['west'],
    frameCounts: { 'west': 8 },
  },
  'enemies/moonbear/death': {
    path: '/sprites/enemies/moonbear/animations/death.png',
    cols: 8, rows: 1,
    dirRows: ['west'],
    frameCounts: { 'west': 8 },
  },
  'enemies/moonbear/idle': {
    path: '/sprites/enemies/moonbear/animations/idle.png',
    cols: 8, rows: 1,
    dirRows: ['west'],
    frameCounts: { 'west': 8 },
  },
  'enemies/queen-spider/attack': {
    path: '/sprites/enemies/queen-spider/animations/attack.png',
    cols: 8, rows: 1,
    dirRows: ['west'],
    frameCounts: { 'west': 8 },
  },
  'enemies/queen-spider/death': {
    path: '/sprites/enemies/queen-spider/animations/death.png',
    cols: 4, rows: 1,
    dirRows: ['west'],
    frameCounts: { 'west': 4 },
  },
  'enemies/queen-spider/walk': {
    path: '/sprites/enemies/queen-spider/animations/walk.png',
    cols: 8, rows: 1,
    dirRows: ['west'],
    frameCounts: { 'west': 8 },
  },
  'enemies/slime-king/attack': {
    path: '/sprites/enemies/slime-king/animations/attack.png',
    cols: 8, rows: 1,
    dirRows: ['west'],
    frameCounts: { 'west': 8 },
  },
  'enemies/slime-king/death': {
    path: '/sprites/enemies/slime-king/animations/death.png',
    cols: 8, rows: 1,
    dirRows: ['west'],
    frameCounts: { 'west': 8 },
  },
  'enemies/slime-king/idle': {
    path: '/sprites/enemies/slime-king/animations/idle.png',
    cols: 8, rows: 1,
    dirRows: ['west'],
    frameCounts: { 'west': 8 },
  },
  'enemies/slime-king/walk': {
    path: '/sprites/enemies/slime-king/animations/walk.png',
    cols: 8, rows: 1,
    dirRows: ['west'],
    frameCounts: { 'west': 8 },
  },
  'enemies/slime/attack': {
    path: '/sprites/enemies/slime/animations/attack.png',
    cols: 4, rows: 1,
    dirRows: ['west'],
    frameCounts: { 'west': 4 },
  },
  'enemies/slime/death': {
    path: '/sprites/enemies/slime/animations/death.png',
    cols: 8, rows: 1,
    dirRows: ['west'],
    frameCounts: { 'west': 8 },
  },
  'enemies/slime/walk': {
    path: '/sprites/enemies/slime/animations/walk.png',
    cols: 8, rows: 1,
    dirRows: ['west'],
    frameCounts: { 'west': 8 },
  },
};

/** Look up sheet geometry by entity folder + anim, e.g. ('characters/LS-SWORD-M', 'attack'). */
export function getSheetEntry(entityKey: string, anim: string): SheetEntry | undefined {
  return SPRITE_SHEET_MANIFEST[`${entityKey}/${anim}`];
}
