import { EmitterShape, Blending } from 'r3f-vfx'
import type { VfxPreset } from './preset-types'

// Generic combat/utility effects for all civilizations
export const genericPresets: VfxPreset[] = [
  {
    id: 'gen-hit',
    name: 'Hit Impact',
    category: 'generic',
    categoryLabel: 'Generic',
    emoji: '💢',
    description: 'Universal hit flash with debris',
    props: {
      maxParticles: 500,
      size: [0.05, 0.15],
      colorStart: ['#ffffff', '#ffee88'],
      colorEnd: ['#ff8800'],
      fadeOpacity: [1, 0],
      lifetime: [0.15, 0.5],
      speed: [0.3, 1.0],
      gravity: [0, -2, 0],
      emitterShape: EmitterShape.SPHERE,
      emitterRadius: [0, 0.3],
      startPositionAsDirection: true,
    },
  },
  {
    id: 'gen-burst',
    name: 'Explosion Burst',
    category: 'generic',
    categoryLabel: 'Generic',
    emoji: '💥',
    description: 'Radial explosion with ground bounce',
    props: {
      maxParticles: 1000,
      size: [0.08, 0.2],
      colorStart: ['#ff8800', '#ffcc00'],
      colorEnd: ['#cc2200', '#330000'],
      fadeOpacity: [1, 0],
      lifetime: [0.3, 1.0],
      speed: [0.5, 1.5],
      gravity: [0, -3, 0],
      emitterShape: EmitterShape.SPHERE,
      emitterRadius: [0, 0.2],
      startPositionAsDirection: true,
      blending: Blending.ADDITIVE,
      intensity: 6,
      collision: { plane: { y: 0 }, bounce: 0.4, friction: 0.3 },
    },
  },
  {
    id: 'gen-trail',
    name: 'Movement Trail',
    category: 'generic',
    categoryLabel: 'Generic',
    emoji: '🌀',
    description: 'Persistent movement trail with fade',
    props: {
      maxParticles: 400,
      size: [0.04, 0.1],
      colorStart: ['#66bbff', '#aaddff'],
      colorEnd: ['#2244aa'],
      fadeOpacity: [0.7, 0],
      lifetime: [0.5, 1.5],
      speed: [0.01, 0.03],
      turbulence: { intensity: 0.3, frequency: 0.8, speed: 0.2 },
    },
  },
  {
    id: 'gen-levelup',
    name: 'Level Up',
    category: 'generic',
    categoryLabel: 'Generic',
    emoji: '⭐',
    description: 'Celebratory rising golden stars',
    props: {
      maxParticles: 600,
      size: [0.08, 0.2],
      colorStart: ['#ffdd00', '#ffffff'],
      colorEnd: ['#ff8800'],
      fadeSize: [0.5, 1.5],
      fadeOpacity: [1, 0],
      gravity: [0, 1.5, 0],
      lifetime: [1, 3],
      speed: [0.05, 0.15],
      emitterShape: EmitterShape.DISK,
      emitterRadius: [0.3, 1.0],
      startPositionAsDirection: true,
      blending: Blending.ADDITIVE,
      intensity: 5,
    },
  },
]
