import { EmitterShape } from 'r3f-vfx'
import type { VfxPreset } from './preset-types'

// Linh Sơn — Earth/Mountain/Jungle warriors
// Colors: primary=#f5f0e6, secondary=#8B6914, accent=#D4A017
export const linhSonPresets: VfxPreset[] = [
  {
    id: 'ls-fire',
    name: 'Lửa Rừng (Forest Fire)',
    category: 'linh-son',
    categoryLabel: 'Linh Sơn',
    emoji: '🔥',
    description: 'Rising campfire with ember drift',
    props: {
      maxParticles: 3000,
      size: [0.3, 0.8],
      colorStart: ['#ff6600', '#ffcc00', '#ff0000'],
      colorEnd: ['#ff0000', '#330000'],
      fadeSize: [1, 0.2],
      fadeOpacity: [1, 0],
      gravity: [0, 0.5, 0],
      lifetime: [0.4, 0.8],
      direction: [[-0.3, 0.3], [0.5, 1], [-0.3, 0.3]],
      speed: [0.01, 0.05],
      friction: { intensity: 0.03, easing: 'easeOut' },
      intensity: 10,
    },
  },
  {
    id: 'ls-smoke',
    name: 'Khói Đất (Earth Smoke)',
    category: 'linh-son',
    categoryLabel: 'Linh Sơn',
    emoji: '💨',
    description: 'Dense earthy smoke billowing upward',
    props: {
      maxParticles: 300,
      size: [0.3, 0.6],
      colorStart: ['#8B6914', '#A0845C'],
      colorEnd: ['#333333'],
      fadeSize: [0.5, 1.5],
      fadeOpacity: [0.6, 0],
      gravity: [0, 0.5, 0],
      lifetime: [3, 5],
      direction: [[-0.1, 0.1], [0.3, 0.5], [-0.1, 0.1]],
      speed: [0.02, 0.05],
      turbulence: { intensity: 1.2, frequency: 0.8, speed: 0.3 },
    },
  },
  {
    id: 'ls-earth-slam',
    name: 'Sơn Thể (Earth Slam)',
    category: 'linh-son',
    categoryLabel: 'Linh Sơn',
    emoji: '🌋',
    description: 'Ground impact debris burst — passive ability',
    props: {
      maxParticles: 500,
      size: [0.05, 0.15],
      colorStart: ['#D4A017', '#8B6914'],
      colorEnd: ['#553311'],
      fadeOpacity: [1, 0],
      lifetime: [0.5, 1.2],
      speed: [0.3, 0.8],
      gravity: [0, -2, 0],
      emitterShape: EmitterShape.DISK,
      emitterRadius: [0, 0.5],
      startPositionAsDirection: true,
      collision: { plane: { y: 0 }, bounce: 0.3, friction: 0.5 },
    },
  },
  {
    id: 'ls-heal',
    name: 'Chữa Lành (Forest Heal)',
    category: 'linh-son',
    categoryLabel: 'Linh Sơn',
    emoji: '🌿',
    description: 'Rising green motes with golden pollen',
    props: {
      maxParticles: 400,
      size: [0.04, 0.12],
      colorStart: ['#88dd44', '#D4A017'],
      colorEnd: ['#ffdd33'],
      fadeOpacity: [0.8, 0],
      gravity: [0, 0.3, 0],
      lifetime: [2, 4],
      direction: [[-0.2, 0.2], [0.5, 1], [-0.2, 0.2]],
      speed: [0.01, 0.03],
      turbulence: { intensity: 0.5, frequency: 1.2, speed: 0.2 },
      intensity: 3,
    },
  },
]
