import type { MeshlinePreset } from './preset-types'

/**
 * Meshline-based weapon FX presets — slash arcs, beams, projectile trails.
 * Built on `makio-meshline`. Use additive + bloom for the best look.
 */
export const meshlinePresets: MeshlinePreset[] = [
  {
    id: 'ml-slash-horizontal',
    kind: 'meshline',
    name: 'Horizontal Slash',
    category: 'weapon-fx',
    categoryLabel: 'Weapon FX',
    emoji: '⚔️',
    description: 'Wide horizontal sword slash arc',
    shape: 'arc',
    shapeParams: { segments: 48, radius: 1.4, arcAngle: Math.PI * 0.85 },
    color: '#ffffff',
    gradientColor: '#88ccff',
    lineWidth: 18,
    opacity: 0.95,
    additive: true,
    rotation: [0, 0, 0],
  },
  {
    id: 'ml-slash-diagonal',
    kind: 'meshline',
    name: 'Diagonal Slash',
    category: 'weapon-fx',
    categoryLabel: 'Weapon FX',
    emoji: '🗡️',
    description: 'Top-down katana slash',
    shape: 'arc',
    shapeParams: { segments: 48, radius: 1.6, arcAngle: Math.PI * 0.75 },
    color: '#ffeecc',
    gradientColor: '#ff6644',
    lineWidth: 14,
    opacity: 1,
    additive: true,
    rotation: [0, 0, Math.PI * 0.35],
  },
  {
    id: 'ml-slash-spin',
    kind: 'meshline',
    name: 'Spin Slash (full circle)',
    category: 'weapon-fx',
    categoryLabel: 'Weapon FX',
    emoji: '🌀',
    description: 'Full 360° whirlwind slash',
    shape: 'circle',
    shapeParams: { segments: 64, radius: 1.5 },
    color: '#aaffee',
    gradientColor: '#3388ff',
    lineWidth: 12,
    opacity: 0.85,
    additive: true,
    rotation: [Math.PI / 2, 0, 0],
  },
  {
    id: 'ml-beam-laser',
    kind: 'meshline',
    name: 'Laser Beam',
    category: 'weapon-fx',
    categoryLabel: 'Weapon FX',
    emoji: '⚡',
    description: 'Straight high-energy beam',
    shape: 'line',
    shapeParams: {
      segments: 32,
      start: [0, 0, 0],
      end: [4, 0, 0],
    },
    color: '#ffffff',
    gradientColor: '#00ffcc',
    lineWidth: 22,
    opacity: 1,
    additive: true,
  },
  {
    id: 'ml-beam-lightning',
    kind: 'meshline',
    name: 'Lightning Bolt',
    category: 'weapon-fx',
    categoryLabel: 'Weapon FX',
    emoji: '⚡',
    description: 'Jagged sine-wave lightning',
    shape: 'sine',
    shapeParams: { wavelengths: 6, segments: 96, amplitude: 0.25, length: 4 },
    color: '#ffffff',
    gradientColor: '#88ddff',
    lineWidth: 10,
    opacity: 0.95,
    additive: true,
  },
  {
    id: 'ml-projectile-trail',
    kind: 'meshline',
    name: 'Projectile Trail',
    category: 'weapon-fx',
    categoryLabel: 'Weapon FX',
    emoji: '💫',
    description: 'Tapered trail for fast projectile',
    shape: 'line',
    shapeParams: {
      segments: 32,
      start: [-2, 0, 0],
      end: [0, 0, 0],
    },
    color: '#ffaa44',
    gradientColor: '#ff2200',
    lineWidth: 14,
    opacity: 0.9,
    additive: true,
  },
  {
    id: 'ml-spiral-charge',
    kind: 'meshline',
    name: 'Spiral Charge-up',
    category: 'weapon-fx',
    categoryLabel: 'Weapon FX',
    emoji: '🌪️',
    description: 'Helix spiral wrapping a target',
    shape: 'spiral',
    shapeParams: { segments: 128, radius: 1.0, spiralTurns: 4, spiralHeight: 2 },
    color: '#ffffff',
    gradientColor: '#cc44ff',
    lineWidth: 8,
    opacity: 0.85,
    additive: true,
  },
]
