import { EmitterShape, Blending } from 'r3f-vfx'
import type { VfxPreset } from './preset-types'

// Thiên Lữ — Celestial/Stars/Wind nomads
export const thienLuPresets: VfxPreset[] = [
  {
    id: 'tl-stardust',
    name: 'Tinh Bụi (Stardust)',
    category: 'thien-lu',
    categoryLabel: 'Thiên Lữ',
    emoji: '✨',
    description: 'Gentle golden stardust drifting, "Tinh Lộ" passive',
    props: {
      maxParticles: 1000,
      size: [0.03, 0.08],
      colorStart: ['#ffffaa', '#ffcc66'],
      colorEnd: ['#aa66ff'],
      fadeOpacity: [0.8, 0],
      gravity: [0, 0.1, 0],
      lifetime: [3, 6],
      speed: [0.005, 0.02],
      emitterShape: EmitterShape.SPHERE,
      emitterRadius: [0.5, 2.0],
      blending: Blending.ADDITIVE,
      intensity: 4,
      turbulence: { intensity: 0.3, frequency: 0.5, speed: 0.1 },
    },
  },
  {
    id: 'tl-comet',
    name: 'Sao Băng (Comet Strike)',
    category: 'thien-lu',
    categoryLabel: 'Thiên Lữ',
    emoji: '☄️',
    description: 'Fast comet with luminous tail',
    props: {
      maxParticles: 800,
      size: [0.05, 0.15],
      colorStart: ['#ccddff', '#ffffff'],
      colorEnd: ['#ffaa33'],
      fadeOpacity: [1, 0],
      lifetime: [0.3, 1.0],
      speed: [0.5, 1.5],
      direction: [[0.3, 0.6], [-0.8, -0.3], [0.3, 0.6]],
      blending: Blending.ADDITIVE,
      intensity: 6,
      emitterShape: EmitterShape.CONE,
      emitterRadius: [0, 0.15],
      emitterAngle: Math.PI / 12,
    },
  },
  {
    id: 'tl-wind',
    name: 'Thiên Phong (Celestial Wind)',
    category: 'thien-lu',
    categoryLabel: 'Thiên Lữ',
    emoji: '🌬️',
    description: 'Swirling violet-cyan wind currents',
    props: {
      maxParticles: 500,
      size: [0.04, 0.1],
      colorStart: ['#99bbff', '#cc99ff'],
      colorEnd: ['#6633cc'],
      fadeOpacity: [0.6, 0],
      lifetime: [1.5, 3],
      speed: [0.1, 0.3],
      direction: [[0.5, 1], [-0.1, 0.2], [-0.3, 0.3]],
      turbulence: { intensity: 2.0, frequency: 1.0, speed: 0.5 },
    },
  },
  {
    id: 'tl-constellation',
    name: 'Tinh Tùy (Constellation)',
    category: 'thien-lu',
    categoryLabel: 'Thiên Lữ',
    emoji: '🌟',
    description: 'Pulsing star nodes forming patterns',
    props: {
      maxParticles: 300,
      size: [0.06, 0.14],
      colorStart: ['#ffffcc', '#ffddaa'],
      colorEnd: ['#7744cc'],
      fadeOpacity: [1, 0],
      lifetime: [2, 5],
      speed: [0.01, 0.05],
      emitterShape: EmitterShape.SPHERE,
      emitterRadius: [1.0, 2.5],
      blending: Blending.ADDITIVE,
      intensity: 5,
      attractToCenter: true,
    },
  },
]
